# Generated by Django 3.2.6 on 2021-08-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stage',
            field=models.SmallIntegerField(choices=[(1, 'Выбор действия'), (2, 'Ввод количества гостей'), (3, 'Ввод времени')], default=1, verbose_name='Этап бронирования'),
        ),
    ]
