# Generated by Django 3.2.6 on 2021-08-19 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_profile_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_network',
            field=models.SmallIntegerField(choices=[(1, 'Telegram')], default=1, verbose_name='Социальная сеть'),
        ),
    ]
