# Generated by Django 3.2.6 on 2021-08-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_profile_social_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='social_network',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Telegram')], null=True, verbose_name='Социальная сеть'),
        ),
    ]
